# Generated by Django 4.2.4 on 2023-09-03 21:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_materia', to=settings.AUTH_USER_MODEL)),
                ('profes', models.ManyToManyField(blank=True, related_name='materias_relacionadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios_Partes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('horas', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(12)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creador_de_materia', to=settings.AUTH_USER_MODEL)),
                ('profes', models.ManyToManyField(blank=True, related_name='horarios_relacionados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_nom', models.TextField()),
                ('grado_num', models.TextField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('alumnos', models.ManyToManyField(blank=True, related_name='grado_alumnos', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_grado', to=settings.AUTH_USER_MODEL)),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grado_director', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ManyToManyField(blank=True, related_name='horario_establecido', to='informacion.materias')),
                ('materias', models.ManyToManyField(blank=True, related_name='grados_relacionados', to='informacion.materias')),
            ],
        ),
    ]
