# Generated by Django 4.2.4 on 2023-09-04 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('informacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_materia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materias',
            name='profes',
            field=models.ManyToManyField(blank=True, related_name='materias_relacionadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horarios_partes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creador_de_materia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horarios_partes',
            name='profes',
            field=models.ManyToManyField(blank=True, related_name='horarios_relacionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grado',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='grado_alumnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grado',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_grado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grado',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grado_director', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grado',
            name='horario',
            field=models.ManyToManyField(blank=True, related_name='horario_establecido', to='informacion.materias'),
        ),
        migrations.AddField(
            model_name='grado',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='grados_relacionados', to='informacion.materias'),
        ),
    ]
