# Generated by Django 4.2.4 on 2023-09-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='alumnos',
        ),
        migrations.RemoveField(
            model_name='grado',
            name='director',
        ),
    ]
