# Generated by Django 4.2.4 on 2023-11-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodiario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariodiario',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
