# Generated by Django 4.2.4 on 2023-11-28 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0003_horariodiario_hora_fin_horariodiario_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariodiario',
            name='Hora',
        ),
    ]
