# Generated by Django 4.2.4 on 2023-09-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0003_remove_grado_alumnos_remove_grado_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='horario',
        ),
        migrations.AddField(
            model_name='grado',
            name='horario',
            field=models.ManyToManyField(blank=True, related_name='horario_grado', to='informacion.horariodiario'),
        ),
    ]
