# Generated by Django 4.2.4 on 2023-09-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('informacion', '0004_remove_grado_horario_grado_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodiario',
            name='jueves',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_grado_4', to='informacion.materias'),
        ),
        migrations.AddField(
            model_name='horariodiario',
            name='lunes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_grado_1', to='informacion.materias'),
        ),
        migrations.AddField(
            model_name='horariodiario',
            name='martes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_grado_2', to='informacion.materias'),
        ),
        migrations.AddField(
            model_name='horariodiario',
            name='miercoles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_grado_3', to='informacion.materias'),
        ),
        migrations.AddField(
            model_name='horariodiario',
            name='viernes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_grado_5', to='informacion.materias'),
        ),
        migrations.AddField(
            model_name='materias',
            name='profe1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_1', to='users.customuserprofesores'),
        ),
        migrations.AlterField(
            model_name='materias',
            name='profe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesor_0', to='users.customuserprofesores'),
        ),
    ]
