# Generated by Django 4.2.4 on 2023-09-03 22:04

from django.db import migrations, models
import profesores.models


class Migration(migrations.Migration):

    dependencies = [
        ('profesores', '0002_alter_customuserprofesores_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofesores',
            name='foto',
            field=models.ImageField(blank=True, default='profesores/profile.png', null=True, upload_to=profesores.models.user_directory_path_profile),
        ),
    ]
