# Generated by Django 4.2.4 on 2023-10-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuseradministrador',
            name='tipo_usuario',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Acudiente', 'Acudiente'), ('Alumno', 'Alumno'), ('Gestor', 'Gestor'), ('Administrador', 'Administrador')], default='Administrador', max_length=50),
        ),
    ]
