# Generated by Django 4.2.4 on 2023-09-13 02:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='introduccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuseradministrador',
            name='tipo_usuario',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Acudiente', 'Acudiente'), ('Alumno', 'Alumno'), ('Gestor', 'Gestor'), ('Administrador', 'Administrador')], default='Alumno', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuseralumno',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuseralumno',
            name='tipo_usuario',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Acudiente', 'Acudiente'), ('Alumno', 'Alumno'), ('Gestor', 'Gestor'), ('Administrador', 'Administrador')], default='Alumno', max_length=50),
        ),
        migrations.AlterField(
            model_name='customusergestor',
            name='tipo_usuario',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Acudiente', 'Acudiente'), ('Alumno', 'Alumno'), ('Gestor', 'Gestor'), ('Administrador', 'Administrador')], default='Gestor', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuserprofesores',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuserprofesores',
            name='tipo_usuario',
            field=models.CharField(choices=[('Profesor', 'Profesor'), ('Acudiente', 'Acudiente'), ('Alumno', 'Alumno'), ('Gestor', 'Gestor'), ('Administrador', 'Administrador')], default='Profesor', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomUserAcudiente',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tipo_usuario', models.CharField(choices=[('Profesor', 'Profesor'), ('Acudiente', 'Acudiente'), ('Alumno', 'Alumno'), ('Gestor', 'Gestor'), ('Administrador', 'Administrador')], default='Acudiente', max_length=50)),
                ('estudiante', models.ManyToManyField(blank=True, related_name='estudiantes', to='users.customuseralumno')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
