# Generated by Django 4.2.4 on 2023-09-13 19:22

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_introduccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserAcudienteProxy',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Acudiente',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuseracudiente',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
