# Generated by Django 4.2.4 on 2023-11-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuseradministrador_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuseracudiente',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Sin informacion', 'Sin informacion')], default='Sin informacion', max_length=20),
        ),
    ]
