# Generated by Django 4.2.4 on 2023-09-13 02:21

import administradores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuseradministrador',
            name='foto',
            field=models.ImageField(blank=True, default='administradores/profile.png', null=True, upload_to=administradores.models.user_directory_path_profile),
        ),
    ]
